//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsiteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class JP_ApplicationTB
    {
        public int App_Id { get; set; }
        public int User_id { get; set; }
        public int Company_id { get; set; }
        public int Job_Id { get; set; }
        public string Resume { get; set; }
        public System.DateTime App_Date { get; set; }
        public string App_Status { get; set; }
    }
}
