//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsiteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class JP_CompanyTB
    {
        public int company_id { get; set; }
        public string company_Name { get; set; }
        public string company_Address { get; set; }
        public string company_Email { get; set; }
        public long company_Number { get; set; }
        public string company_website { get; set; }
    }
}
