//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsiteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class JP_ExperienceTB
    {
        public int Exp_id { get; set; }
        public int user_id { get; set; }
        public string Jobtittle { get; set; }
        public string Company_Name { get; set; }
        public string Job_location { get; set; }
        public string Role { get; set; }
        public System.DateTime Sart_Date { get; set; }
        public System.DateTime end_Date { get; set; }
        public string Current_status { get; set; }
        public string Skills { get; set; }
        public string Description { get; set; }
    }
}
