//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsiteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class JP_JobpostTB
    {
        public int Job_id { get; set; }
        public int Company_id { get; set; }
        public string Job_Tittle { get; set; }
        public string Job_description { get; set; }
        public string Job_Type { get; set; }
        public string Job_Experience { get; set; }
        public string Job_Skills { get; set; }
        public string Job_Salary { get; set; }
        public System.DateTime Job_enddate { get; set; }
        public string Job_Location { get; set; }
        public string Job_Status { get; set; }
    }
}
